    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ [^/]\.php(/|$) {
        if (!-f $document_root$fastcgi_script_name) {
            return 404;
        }
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass $php_server:9000;
        include fastcgi.conf;
        fastcgi_param  PATH_INFO  $fastcgi_path_info;
    }
